Repository LinuxCNC/linuxcnc, pull requests merged in 2022-12, with the labels that each got.

#2172 Fix obsolete link to documentation in image-to-gcode(1).
  docs/man/man1/image-to-gcode.1
Labels: affects 2.8

#1830 Gmoccapy: Pass numbers to user tabs to allow numeric entry
  src/emc/usr_intf/gmoccapy/gmoccapy.py
Labels: affects gmoccapy

#2165 Corrected rtapi_io(3rtapi) man page fixing typos and adding references.
  docs/man/man3/rtapi_io.3rtapi
Labels: affects 2.9

#2164 Added rtapi_ioperm() declaration for hal_speaker
  docs/man/man3/rtapi_io.3rtapi
  src/hal/drivers/hal_speaker.c
  src/rtapi/rtapi_io.h
Labels: affects 2.9

#2194 GMOCCAPY 3.4.1
  docs/src/gui/gmoccapy.adoc
  src/emc/usr_intf/gmoccapy/getiniinfo.py
  src/emc/usr_intf/gmoccapy/gmoccapy.glade
  src/emc/usr_intf/gmoccapy/gmoccapy.py
  src/emc/usr_intf/gmoccapy/notification.py
  src/emc/usr_intf/gmoccapy/release_notes.txt
Labels: affects gmoccapy, affects 2.9
