Repository LinuxCNC/linuxcnc, pull requests merged in 2023-03, with the labels that each got.

#2322 docs_hal_revisited
  docs/man/man1/qtvcp.1
  docs/man/man9/hostmot2.9
  docs/man/man9/rosekins.9
  docs/man/man9/sserial.9
  docs/src/gui/ngcgui.adoc
  docs/src/gui/qtdragon.adoc
  docs/src/gui/qtvcp.adoc
  docs/src/hal/basic-hal.adoc
  docs/src/hal/canonical-devices.adoc
  docs/src/hal/comp.adoc
  docs/src/hal/components.adoc
  docs/src/hal/general-ref.adoc
  docs/src/hal/hal-examples.adoc
  docs/src/hal/halmodule.adoc
  docs/src/hal/halshow.adoc
  docs/src/hal/haltcl.adoc
  docs/src/hal/halui-examples.adoc
  docs/src/hal/parallel-port.adoc
  docs/src/hal/rtcomps.adoc
  docs/src/hal/tools.adoc
  docs/src/hal/twopass.adoc
  docs/src/plasma/plasma-cnc-primer.adoc
  docs/src/plasma/qtplasmac.adoc
  docs/src/remap/remap.adoc
  docs/src/user/user-concepts.adoc
Labels: documentation

#2383 Gmoccapy 3.4.2.1
  configs/sim/gmoccapy/lathe_configs/gmoccapy_lathe.pref
  configs/sim/gmoccapy/lathe_configs/lathe.ini
  configs/sim/gmoccapy/lathe_configs/lathe_macros.ini
  configs/sim/gmoccapy/non_trivial_kinematics/Gantry/gantry_mm.ini
  configs/sim/gmoccapy/non_trivial_kinematics/scara/scara.ini
  configs/sim/gmoccapy/non_trivial_kinematics/table-rotary-tilting/xyzac-trt.ini
  docs/src/gui/images/gmoccapy_3_axis.png
  docs/src/gui/images/gmoccapy_3_axis_mid.png
  docs/src/gui/images/gmoccapy_5_axis.png
  docs/src/gui/images/gmoccapy_5_axis_mid.png
  lib/python/gladevcp/iconview.py
  src/emc/usr_intf/gmoccapy/gmoccapy.glade
  src/emc/usr_intf/gmoccapy/gmoccapy.py
  src/emc/usr_intf/gmoccapy/icon_theme_helper.py
  src/emc/usr_intf/gmoccapy/release_notes.txt
Labels: affects gmoccapy

#2406 gladevcp: add font properties to drowidget
  docs/src/gui/gladevcp.adoc
  lib/python/gladevcp/drowidget.py
Labels: affects gmoccapy, affects 2.9
